import { afterEach, beforeEach, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({admin:vi.fn(),send:vi.fn(),updates:vi.fn(),student:vi.fn(),challenge:vi.fn(),claim:vi.fn()}));
vi.mock("./welcome-invite",()=>({createWelcomeInvite:vi.fn().mockResolvedValue("https://lessonara.example/student/invite/test-invite")}));
vi.mock("@/lib/supabase/server",()=>({createAdminClient:mocks.admin}));
vi.mock("@/lib/email",async original=>{const emailModule=await original<typeof import("@/lib/email")>();return {...emailModule,sendEmail:mocks.send};});
import {processEmails} from "./outbox";
import {seal} from "./crypto";
import {EmailSendError} from "../email";
const base={id:"job",event_key:"welcome/student/1",lease_id:"lease",student_id:"student",recipient:"alice@example.com",template:"welcome",payload:{},attempts:1,delivery:null,expires_at:"2026-10-09T12:00:00Z"};
function db(){return {rpc:mocks.claim,from(table:string){let values:unknown;const query={select(){return query;},eq(){return query;},is(){return query;},gt(){return query;},update(value:unknown){values=value;return query;},async maybeSingle(){return table==="students"?mocks.student():mocks.challenge();},then(resolve:(value:unknown)=>unknown){mocks.updates(values);return Promise.resolve({error:null}).then(resolve);}};return query;}};}
beforeEach(()=>{vi.resetAllMocks();vi.useFakeTimers();vi.setSystemTime(new Date("2026-10-08T12:00:00Z"));vi.stubEnv("EMAIL_ENCRYPTION_KEY","01".repeat(32));vi.stubEnv("EMAIL_FROM","Lessonara <aulas@example.com>");vi.stubEnv("APP_URL","https://lessonara.example");mocks.admin.mockReturnValue(db());mocks.claim.mockResolvedValue({data:[base],error:null});mocks.student.mockResolvedValue({data:{name:"Alice",email:"alice@example.com",active:true,teachers:{name:"Prof",email:"teacher@example.com"}},error:null});mocks.challenge.mockResolvedValue({data:{id:"challenge"},error:null});mocks.send.mockResolvedValue({id:"provider"});});
afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();});
it("revalida aluno e envia com idempotência, registrando aceitação sem guardar conteúdo",async()=>{expect(await processEmails()).toEqual({sent:1,failed:0,pending:0,cancelled:0});expect(mocks.send).toHaveBeenCalledWith(expect.objectContaining({to:"alice@example.com"}),"lessonara/job");expect(mocks.updates).toHaveBeenCalledWith(expect.objectContaining({status:"sent",provider_id:"provider",payload:{},delivery:null}));});
it("erro temporário mantém corpo criptografado para retry com backoff",async()=>{mocks.send.mockRejectedValue(new EmailSendError("rate_limit_exceeded",true));expect((await processEmails()).pending).toBe(1);expect(mocks.updates).toHaveBeenCalledWith(expect.objectContaining({status:"pending",available_at:"2026-10-08T12:00:30.000Z"}));});
it("falha permanente não é reenviada automaticamente",async()=>{mocks.send.mockRejectedValue(new EmailSendError("validation_error",false));expect((await processEmails()).failed).toBe(1);expect(mocks.updates).toHaveBeenCalledWith(expect.objectContaining({status:"failed",last_error:"validation_error",delivery:null,payload:{}}));});
it("retry preserva o remetente e conteúdo originais",async()=>{const body={to:"alice@example.com",from:"Lessonara <old@example.com>",subject:"Original",html:"Texto",text:"Texto"};mocks.claim.mockResolvedValue({data:[{...base,delivery:{sealed:seal(body)}}],error:null});await processEmails();expect(mocks.send).toHaveBeenCalledWith(body,"lessonara/job");});
it.each([{email:"changed@example.com",active:true},{email:"alice@example.com",active:false}])("não envia convite obsoleto ao mudar cadastro",async student=>{mocks.student.mockResolvedValue({data:student,error:null});expect((await processEmails()).cancelled).toBe(1);expect(mocks.send).not.toHaveBeenCalled();});
it("código consumido/substituído não sai da fila mesmo que exista um corpo pronto",async()=>{mocks.claim.mockResolvedValue({data:[{...base,student_id:null,template:"otp",event_key:"otp/challenge",payload:{sealed:seal({code:"123456"})}}],error:null});mocks.challenge.mockResolvedValue({data:null,error:null});expect((await processEmails()).cancelled).toBe(1);expect(mocks.send).not.toHaveBeenCalled();});
it("não envia OTP se o prazo terminar durante o processamento",async()=>{mocks.claim.mockResolvedValue({data:[{...base,student_id:null,template:"otp",event_key:"otp/challenge",expires_at:"2026-10-08T11:59:59Z",payload:{sealed:seal({code:"123456"})}}],error:null});expect((await processEmails()).failed).toBe(1);expect(mocks.send).not.toHaveBeenCalled();});
