"use client";
import { useState, useTransition } from "react";
import { addDays, formatDate } from "@/lib/dates";
import type { HolidaySettings, HolidayRow } from "@/lib/holiday-data";
import { addHoliday, removeHoliday, saveHolidayRule } from "@/app/(painel)/config/holiday-actions";

export function HolidaySettingsForm({settings,holidays,today,locked,ready}:{settings:HolidaySettings|null;holidays:HolidayRow[];today:string;locked:boolean;ready:boolean}) {
 const [enabled,setEnabled]=useState(settings?.enabled ?? false);
 const [policy,setPolicy]=useState(settings?.policy ?? "consume");
 const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 const [removing,setRemoving]=useState<string|null>(null);
 return <section className="card space-y-5"><div><h2 className="h2">Feriados da empresa</h2><p className="text-xs leading-relaxed text-muted">Uma regra para todos os seus alunos. Você cadastra as datas, incluindo feriados locais.</p></div>
 {!ready ? <p role="status" className="text-sm text-muted">A configuração de feriados ainda está em preparação.</p> : <>
 <form onSubmit={event=>{event.preventDefault();setMessage("");startTransition(async()=>{try{const result=await saveHolidayRule(enabled,policy);setMessage(result.ok?"Regra de feriados salva.":result.message);}catch{setMessage("Não foi possível salvar a regra.");}});}} className="space-y-4">
 <fieldset disabled={locked||pending} className="space-y-4 disabled:opacity-70"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>Considerar feriados no pacote</label>
 <div className="space-y-3"><label className="flex items-start gap-3 rounded-xl border border-line p-4"><input type="radio" name="holiday-policy" value="consume" checked={policy==="consume"} onChange={()=>setPolicy("consume")} disabled={!enabled} className="mt-1"/><span><b className="text-sm font-medium">Feriado consome uma aula</b><span className="mt-1 block text-xs text-muted">A aula não acontece, mas desconta um crédito do pacote.</span></span></label>
 <label className="flex items-start gap-3 rounded-xl border border-line p-4"><input type="radio" name="holiday-policy" value="preserve" checked={policy==="preserve"} onChange={()=>setPolicy("preserve")} disabled={!enabled} className="mt-1"/><span><b className="text-sm font-medium">Feriado mantém o crédito</b><span className="mt-1 block text-xs text-muted">Sem desconto. O pacote passa a cobrir o próximo encontro; não cria créditos extras.</span></span></label></div>
 <button className="btn" type="submit">{pending?"Salvando…":"Salvar regra de feriados"}</button></fieldset>
 <p className="text-xs leading-relaxed text-muted">{locked?"Regra travada: a primeira aula em feriado já foi afetada. Isso protege os saldos e o histórico." : "A regra pode mudar até a primeira aula afetada. Depois disso, ativação e forma de contagem ficam travadas."} {settings?.effective_from&&`Válida a partir de ${formatDate(settings.effective_from)}.`}</p></form>
 <div className="border-t border-line pt-5"><h3 className="mb-3 text-sm font-semibold">Datas cadastradas</h3><p className="mb-4 text-xs leading-relaxed text-muted">Cadastre a partir de amanhã para preservar aulas já registradas. Feriados de hoje ou anteriores não podem ser alterados. Reposições lançadas manualmente continuam consumindo crédito.</p>
 <form onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setMessage("");startTransition(async()=>{try{const result=await addHoliday(String(data.get("date")),String(data.get("name")));setMessage(result.ok?"Feriado cadastrado.":result.message);if(result.ok)form.reset();}catch{setMessage("Não foi possível cadastrar o feriado.");}});}} className="grid grid-cols-1 gap-3 sm:grid-cols-[1fr_1.5fr_auto]">
 <div><label className="label" htmlFor="holiday-date">Data</label><input className="input" id="holiday-date" name="date" type="date" min={addDays(today,1)} required disabled={pending}/></div><div><label className="label" htmlFor="holiday-name">Nome do feriado</label><input className="input" id="holiday-name" name="name" maxLength={120} required placeholder="Ex.: Feriado municipal" disabled={pending}/></div><button className="btn self-end" disabled={pending}>Adicionar feriado</button></form>
 {!settings?.enabled&&<p className="mt-3 text-xs text-muted">As datas ficam guardadas, mas só afetam os pacotes quando a regra está ativada e salva.</p>}
 <ul className="mt-5 divide-y divide-line">{holidays.map(holiday=><li key={holiday.id} className="flex flex-wrap items-center gap-3 py-3 text-sm"><span className="text-muted">{formatDate(holiday.date)}</span><span className="flex-1">{holiday.name}</span>{holiday.date>today?<><button className="btn-xs text-bad" disabled={pending} onClick={()=>{if(removing!==holiday.id){setRemoving(holiday.id);return;}startTransition(async()=>{try{const result=await removeHoliday(holiday.id);setMessage(result.ok?"Feriado removido.":result.message);setRemoving(null);}catch{setMessage("Não foi possível remover o feriado.");}});}}>{removing===holiday.id?"Confirmar remoção":"Remover"}</button>{removing===holiday.id&&<button className="btn-xs" disabled={pending} onClick={()=>setRemoving(null)}>Cancelar</button>}</>:<span className="text-xs text-muted">Histórico preservado</span>}</li>)}</ul>{!holidays.length&&<p className="mt-4 text-xs text-muted">Nenhum feriado cadastrado ainda.</p>}</div></>}{message&&<p role="status" className="text-xs text-accent">{message}</p>}</section>;
}
