import { activityStatus,type Activity } from "@/lib/activities";
import { activityDateTime } from "@/lib/activity-dates";
import { formatDate } from "@/lib/dates";
import { formatFileSize } from "@/lib/document-rules";
import { StudentActivityUpload } from "./student-activity-upload";
export type StudentActivity=Omit<Activity,"studentId"|"studentName"|"documentId">;
export function StudentActivities({activities,slug,today}:{activities:StudentActivity[];slug:string;today:string}){
 return <div className="space-y-5"><section className="card"><div className="section-heading"><div><h2>Minhas atividades<span className="count-badge">{activities.length}</span></h2><p>Receba o exercício, envie sua entrega e acompanhe a conferência.</p></div></div>{!activities.length&&<p className="mt-5 text-sm text-muted">As atividades que sua professora enviar aparecem aqui.</p>}</section>{activities.map(activity=><section key={activity.id} className="card activity-card"><div className="section-heading"><h3>{activity.title}</h3><span className={`balance-pill ${activity.due_on&&activity.due_on<today&&!activity.submission?.submitted_at&&!activity.archived_at?"balance-warning":""}`}>{activityStatus(activity,today)}</span></div><p className="activity-dates">Enviada em {activityDateTime(activity.assigned_at)} · {activity.due_on?`Entregar até ${formatDate(activity.due_on)}`:"Sem prazo de entrega"}</p>{activity.instructions&&<p className="activity-instructions">{activity.instructions}</p>}{activity.documentName&&<a className="btn-ghost mt-4" href={`/a/${encodeURIComponent(slug)}/atividades/${activity.id}/arquivo`} target="_blank" rel="noreferrer">Baixar exercício · {activity.documentName}</a>}{activity.submission?.submitted_at?<div className="activity-delivery"><h4>Sua entrega</h4><p className="text-xs text-muted">{activityDateTime(activity.submission.submitted_at)}{activity.submission.submitted_late?" · entregue após o prazo":""}</p><p className="mt-2 text-sm">{activity.submission.file_name} · {formatFileSize(activity.submission.byte_size)}</p>{activity.submission.note&&<p className="activity-instructions text-xs">{activity.submission.note}</p>}{activity.submission.status==="ready"?<a className="btn-xs mt-3 inline-block" href={`/a/${encodeURIComponent(slug)}/atividades/${activity.id}/entrega`} target="_blank" rel="noreferrer">Baixar minha entrega</a>:<p className="mt-3 text-xs text-muted">O arquivo da entrega foi removido. O registro de entrega está preservado.</p>}</div>:!activity.archived_at?<StudentActivityUpload slug={slug} activityId={activity.id} incomplete={Boolean(activity.submission)}/>:<p className="mt-5 text-sm text-muted">Esta atividade foi arquivada e não recebe novas entregas.</p>}{activity.reviewed_at&&<div className="activity-feedback"><h4>Conferência da professora</h4><p className="text-xs text-muted">Conferida em {activityDateTime(activity.reviewed_at)}</p><p className="activity-instructions">{activity.feedback||"Sua professora conferiu a atividade."}</p></div>}{activity.due_on&&!activity.submission?.submitted_at&&!activity.archived_at&&<p className="mt-4 text-[11px] text-muted">Entregas após o prazo continuam permitidas e ficam sinalizadas para sua professora.</p>}</section>)}</div>;
}
